/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.brukhman.sparser.language.analysis;

import org.brukhman.sparser.language.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAGrammar(AGrammar node);
    void caseAPlusExp(APlusExp node);
    void caseAMinusExp(AMinusExp node);
    void caseADivExp(ADivExp node);
    void caseAMultExp(AMultExp node);
    void caseATextualExp(ATextualExp node);
    void caseARandomX2Exp(ARandomX2Exp node);
    void caseANumberExp(ANumberExp node);
    void caseAT1Textual(AT1Textual node);
    void caseAT2Textual(AT2Textual node);
    void caseAT3Textual(AT3Textual node);

    void caseTLPar(TLPar node);
    void caseTRPar(TRPar node);
    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTSemi(TSemi node);
    void caseTBlank(TBlank node);
    void caseTNumber(TNumber node);
    void caseTOne(TOne node);
    void caseTTwo(TTwo node);
    void caseTThree(TThree node);
    void caseTRandom(TRandom node);
    void caseEOF(EOF node);
}
