/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.brukhman.sparser.parser.analysis;

import java.util.*;
import org.brukhman.sparser.parser.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPGrammar().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inAGrammar(AGrammar node)
    {
        defaultIn(node);
    }

    public void outAGrammar(AGrammar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGrammar(AGrammar node)
    {
        inAGrammar(node);
        {
            List<PExp> copy = new ArrayList<PExp>(node.getExp());
            for(PExp e : copy)
            {
                e.apply(this);
            }
        }
        outAGrammar(node);
    }

    public void inAPlusExp(APlusExp node)
    {
        defaultIn(node);
    }

    public void outAPlusExp(APlusExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPlusExp(APlusExp node)
    {
        inAPlusExp(node);
        if(node.getL() != null)
        {
            node.getL().apply(this);
        }
        if(node.getR() != null)
        {
            node.getR().apply(this);
        }
        outAPlusExp(node);
    }

    public void inAMinusExp(AMinusExp node)
    {
        defaultIn(node);
    }

    public void outAMinusExp(AMinusExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMinusExp(AMinusExp node)
    {
        inAMinusExp(node);
        if(node.getL() != null)
        {
            node.getL().apply(this);
        }
        if(node.getR() != null)
        {
            node.getR().apply(this);
        }
        outAMinusExp(node);
    }

    public void inADivExp(ADivExp node)
    {
        defaultIn(node);
    }

    public void outADivExp(ADivExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivExp(ADivExp node)
    {
        inADivExp(node);
        if(node.getL() != null)
        {
            node.getL().apply(this);
        }
        if(node.getR() != null)
        {
            node.getR().apply(this);
        }
        outADivExp(node);
    }

    public void inAMultExp(AMultExp node)
    {
        defaultIn(node);
    }

    public void outAMultExp(AMultExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultExp(AMultExp node)
    {
        inAMultExp(node);
        if(node.getL() != null)
        {
            node.getL().apply(this);
        }
        if(node.getR() != null)
        {
            node.getR().apply(this);
        }
        outAMultExp(node);
    }

    public void inATextualExp(ATextualExp node)
    {
        defaultIn(node);
    }

    public void outATextualExp(ATextualExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATextualExp(ATextualExp node)
    {
        inATextualExp(node);
        {
            List<PTextual> copy = new ArrayList<PTextual>(node.getTextual());
            for(PTextual e : copy)
            {
                e.apply(this);
            }
        }
        outATextualExp(node);
    }

    public void inARandomX2Exp(ARandomX2Exp node)
    {
        defaultIn(node);
    }

    public void outARandomX2Exp(ARandomX2Exp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARandomX2Exp(ARandomX2Exp node)
    {
        inARandomX2Exp(node);
        if(node.getR1() != null)
        {
            node.getR1().apply(this);
        }
        if(node.getR2() != null)
        {
            node.getR2().apply(this);
        }
        outARandomX2Exp(node);
    }

    public void inANumberExp(ANumberExp node)
    {
        defaultIn(node);
    }

    public void outANumberExp(ANumberExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumberExp(ANumberExp node)
    {
        inANumberExp(node);
        if(node.getNumber() != null)
        {
            node.getNumber().apply(this);
        }
        outANumberExp(node);
    }

    public void inAT1Textual(AT1Textual node)
    {
        defaultIn(node);
    }

    public void outAT1Textual(AT1Textual node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAT1Textual(AT1Textual node)
    {
        inAT1Textual(node);
        if(node.getOne() != null)
        {
            node.getOne().apply(this);
        }
        outAT1Textual(node);
    }

    public void inAT2Textual(AT2Textual node)
    {
        defaultIn(node);
    }

    public void outAT2Textual(AT2Textual node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAT2Textual(AT2Textual node)
    {
        inAT2Textual(node);
        if(node.getTwo() != null)
        {
            node.getTwo().apply(this);
        }
        outAT2Textual(node);
    }

    public void inAT3Textual(AT3Textual node)
    {
        defaultIn(node);
    }

    public void outAT3Textual(AT3Textual node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAT3Textual(AT3Textual node)
    {
        inAT3Textual(node);
        if(node.getThree() != null)
        {
            node.getThree().apply(this);
        }
        outAT3Textual(node);
    }
}
