/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.brukhman.sparser.parser.node;

import org.brukhman.sparser.parser.analysis.*;

@SuppressWarnings("nls")
public final class AT2Textual extends PTextual
{
    private TTwo _two_;

    public AT2Textual()
    {
        // Constructor
    }

    public AT2Textual(
        @SuppressWarnings("hiding") TTwo _two_)
    {
        // Constructor
        setTwo(_two_);

    }

    @Override
    public Object clone()
    {
        return new AT2Textual(
            cloneNode(this._two_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAT2Textual(this);
    }

    public TTwo getTwo()
    {
        return this._two_;
    }

    public void setTwo(TTwo node)
    {
        if(this._two_ != null)
        {
            this._two_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._two_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._two_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._two_ == child)
        {
            this._two_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._two_ == oldChild)
        {
            setTwo((TTwo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
