/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.brukhman.sparser.parser.node;

import org.brukhman.sparser.parser.analysis.*;

@SuppressWarnings("nls")
public final class TRandom extends Token
{
    public TRandom()
    {
        super.setText("random_digit");
    }

    public TRandom(int line, int pos)
    {
        super.setText("random_digit");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRandom(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRandom(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRandom text.");
    }
}
