/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.brukhman.sparser.parser.node;

import org.brukhman.sparser.parser.analysis.*;

@SuppressWarnings("nls")
public final class TThree extends Token
{
    public TThree()
    {
        super.setText("three");
    }

    public TThree(int line, int pos)
    {
        super.setText("three");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TThree(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTThree(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TThree text.");
    }
}
