/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.brukhman.sparser.parser.parser;

import org.brukhman.sparser.parser.node.*;
import org.brukhman.sparser.parser.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTLPar(@SuppressWarnings("unused") TLPar node)
    {
        this.index = 0;
    }

    @Override
    public void caseTRPar(@SuppressWarnings("unused") TRPar node)
    {
        this.index = 1;
    }

    @Override
    public void caseTPlus(@SuppressWarnings("unused") TPlus node)
    {
        this.index = 2;
    }

    @Override
    public void caseTMinus(@SuppressWarnings("unused") TMinus node)
    {
        this.index = 3;
    }

    @Override
    public void caseTMult(@SuppressWarnings("unused") TMult node)
    {
        this.index = 4;
    }

    @Override
    public void caseTDiv(@SuppressWarnings("unused") TDiv node)
    {
        this.index = 5;
    }

    @Override
    public void caseTSemi(@SuppressWarnings("unused") TSemi node)
    {
        this.index = 6;
    }

    @Override
    public void caseTNumber(@SuppressWarnings("unused") TNumber node)
    {
        this.index = 7;
    }

    @Override
    public void caseTOne(@SuppressWarnings("unused") TOne node)
    {
        this.index = 8;
    }

    @Override
    public void caseTTwo(@SuppressWarnings("unused") TTwo node)
    {
        this.index = 9;
    }

    @Override
    public void caseTThree(@SuppressWarnings("unused") TThree node)
    {
        this.index = 10;
    }

    @Override
    public void caseTRandom(@SuppressWarnings("unused") TRandom node)
    {
        this.index = 11;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 12;
    }
}
