/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.brukhman.sparser.language.node;

import org.brukhman.sparser.language.analysis.*;

@SuppressWarnings("nls")
public final class ARandomX2Exp extends PExp
{
    private TRandom _r1_;
    private TRandom _r2_;

    public ARandomX2Exp()
    {
        // Constructor
    }

    public ARandomX2Exp(
        @SuppressWarnings("hiding") TRandom _r1_,
        @SuppressWarnings("hiding") TRandom _r2_)
    {
        // Constructor
        setR1(_r1_);

        setR2(_r2_);

    }

    @Override
    public Object clone()
    {
        return new ARandomX2Exp(
            cloneNode(this._r1_),
            cloneNode(this._r2_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARandomX2Exp(this);
    }

    public TRandom getR1()
    {
        return this._r1_;
    }

    public void setR1(TRandom node)
    {
        if(this._r1_ != null)
        {
            this._r1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._r1_ = node;
    }

    public TRandom getR2()
    {
        return this._r2_;
    }

    public void setR2(TRandom node)
    {
        if(this._r2_ != null)
        {
            this._r2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._r2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._r1_)
            + toString(this._r2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._r1_ == child)
        {
            this._r1_ = null;
            return;
        }

        if(this._r2_ == child)
        {
            this._r2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._r1_ == oldChild)
        {
            setR1((TRandom) newChild);
            return;
        }

        if(this._r2_ == oldChild)
        {
            setR2((TRandom) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
