/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.brukhman.sparser.language.node;

import org.brukhman.sparser.language.analysis.*;

@SuppressWarnings("nls")
public final class TOne extends Token
{
    public TOne()
    {
        super.setText("one");
    }

    public TOne(int line, int pos)
    {
        super.setText("one");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TOne(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTOne(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TOne text.");
    }
}
