/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.brukhman.sparser.language.node;

import org.brukhman.sparser.language.analysis.*;

@SuppressWarnings("nls")
public final class TTwo extends Token
{
    public TTwo()
    {
        super.setText("two");
    }

    public TTwo(int line, int pos)
    {
        super.setText("two");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTwo(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTwo(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTwo text.");
    }
}
